---
title: "Regional and functional heterogeneity of hypothalamic astrocytes"
author: "Evgenii Tretiakov"
output: workflowr::wflow_html
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(
    autodep        = TRUE,
    cache          = FALSE,
    cache.lazy     = FALSE,
    dev            = c("png", "pdf"),
    echo           = TRUE,
    error          = FALSE,
    fig.align      = "center",
    fig.width      = 8,
    fig.asp        = 0.618,
    message        = FALSE,
    warning        = FALSE
)
# Load tidyverse infrastructure packages
suppressPackageStartupMessages({
    library(here)
    library(tidyverse)
    library(magrittr)
    library(stringr)
    library(skimr)
    library(future)
    library(kableExtra)
})

# Load packages for scRNA-seq analysis and visualisation
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")
  BiocManager::install(c("Seurat", "R.utils", "satijalab/seurat-wrappers", "mojaveazure/seurat-disk", "workflowr", "linxihui/NNLM", "yanwu2014/swne", "YuLab-SMU/ggtree", "pengminshi/mrtree", "glmpca", "scry", "scater", "scuttle", "miQC", "sjessa/ggmin", "glmGamPoi", "Nebulosa"))
}

suppressPackageStartupMessages({
    library(Seurat)
    library(SeuratWrappers)
    library(SeuratDisk)
    library(sctransform)
    library(glmGamPoi)
    library(UpSetR)
    library(patchwork)
    library(swne)
    library(Nebulosa)
    library(mrtree)
})

# Set paths
raw_dir    <- here('../../data/Steuernagel10x')
ext1_dir   <- here('../../data/Ohlig2021')
ext2_dir   <- here('../../data/Lutomska2022')
src_dir    <- here('code')
data_dir   <- here('data')
output_dir <- here('output')
plots_dir  <- here(output_dir, 'figures')
tables_dir <- here(output_dir, 'tables')
# source(here(src_dir, 'genes.R'))

# parallelisation
n_cores <- 20
plan("multisession", workers = n_cores)
options(future.globals.maxSize = 25000 * 1024^2) # 25Gb
plan()

# set seed
reseed <- 42
set.seed(seed = reseed)

# ggplot2 theme
theme_set(ggmin::theme_powerpoint())
```

```{r load-data-hypoMap}
genes.embed <- c("Ndrg2", "Slc1a3", "Gfap", 
                 "S100b", "Agt", "Slc6a11",
                 "Aqp4", "Nfia", "Aldoc", 
                 "Apoe", "Aldh1l1", "Sox9", 
                 "Fgfr3", "Egfr", "Ntrk2")
hypoMap <- readRDS(here(raw_dir, "hypoMap.rds"))

```

```{r check-metadata-summary, render = knitr::normal_print}
skim(hypoMap@meta.data)

```

```{r subset-and-save-h5}
if (!file.exists(here(raw_dir, "hypoMap.h5Seurat"))) {
  SaveH5Seurat(hypoMap, 
               filename = here(raw_dir, "hypoMap.h5Seurat"))
  Convert(here(raw_dir, "hypoMap.h5Seurat"), 
          dest = "h5ad")
}

Idents(hypoMap) <- "C25_named"
astroMap <- 
    hypoMap |>  
    subset(idents = c("C25-18: Astrocytes"))
if (!file.exists(here(raw_dir, "astroMap.h5Seurat"))) {
  SaveH5Seurat(astroMap, 
               filename = here(raw_dir, "astroMap.h5Seurat"))
  Convert(here(raw_dir, "astroMap.h5Seurat"), 
          dest = "h5ad")
}

arcMap <- 
  hypoMap |> 
  subset(subset = (Author_Region == "Arcuate Nucleus/Median Eminence" & Author_Class_Curated %in% c("Astrocytes", "Neurons")) | (Region_summarized == "Arcuate hypothalamic nucleus" & Author_Class_Curated %in% c("Astrocytes", "Neurons"))) |> 
  subset(subset = Author_CellType %in% c("Agrp/Gm8773", "Agrp/Sst", "Pomc/Ttr", "Pomc/Anxa2", "Pomc/Glipr1") | C25_named == "C25-18: Astrocytes" | C66_named %in% c("C66-46: Agrp.GABA-4", "C66-19: Pomc.GLU-5")) |> 
  subset(subset = C66_named %in% c("C66-53: Etnppl.Astrocytes", "C66-54: Lgals3.Astrocytes", "C66-47: Sst.GABA-4", "C66-46: Agrp.GABA-4", "C66-19: Pomc.GLU-5", "C66-41: Tbx3.GABA-1") & Diet == "Normal chow")
if (!file.exists(here(raw_dir, "arcMap.h5Seurat"))) {
  SaveH5Seurat(hypoMap, 
               filename = here(raw_dir, "arcMap.h5Seurat"))
  Convert(here(raw_dir, "arcMap.h5Seurat"), 
          dest = "h5ad")
}
rm(hypoMap)
gc()
```

```{r load-diencephalic-astrocytes}
Ohlig2021_die_astro <- LoadH5Seurat(here(ext1_dir, "astrocytes.h5Seurat"))
```

```{r load-arc}
Deng2020_arc_astro <- LoadH5Seurat(here(data_dir, "deng_2020_arc_chow_astrocytes.h5Seurat"))
Deng2020_arc_all   <- LoadH5Seurat(here(data_dir, "deng_2020_arc_chow_clusters.h5Seurat"))

Lutomska2022_arc_astro <- LoadH5Seurat(here(ext2_dir, "astrocytes.h5Seurat"))
Lutomska2022_arc_astro <- 
  RenameCells(object = Lutomska2022_arc_astro , 
              new.names = str_c(Cells(Lutomska2022_arc_astro),
                                "SRR19578591",
                                sep = "_")
              )
Lutomska2022_arc_all <- LoadH5Seurat(here(ext2_dir, "Lutomska2022.h5Seurat"))
Lutomska2022_arc_all <- 
  RenameCells(object = Lutomska2022_arc_all , 
              new.names = str_c(Cells(Lutomska2022_arc_all),
                                "SRR19578591",
                                sep = "_")
              )
```

```{r update-metadata}
Deng2020_arc_astro@meta.data <-
  Deng2020_arc_astro@meta.data |>
  select(nCount_RNA:nFeature_SCT, study_id, sex, tech, subsets_mito_percent, ident) |> 
  rename(Technology = tech,
         percent_mt = subsets_mito_percent,
         Sex = sex,
         Dataset = study_id,
         Batch_ID = ident) |> 
  mutate(Author_Region = "Arcuate Nucleus/Median Eminence",
         Batch_ID = str_c("Deng10xv3", Batch_ID, sep = "_"),
         Sex = if_else(Sex == "male", "M", "F"),
         Dataset = "Deng10x")
DefaultAssay(object = Deng2020_arc_astro) <- "RNA"
Deng2020_arc_astro <-
  Deng2020_arc_astro |> 
  DietSeurat(assays = "RNA")


Lutomska2022_arc_astro@meta.data <-
  Lutomska2022_arc_astro@meta.data |>
  select(-(SCT_snn_res.0.01:k_tree)) |> 
  rename(Batch_ID = orig.ident) |> 
  mutate(Author_Region = "Arcuate Nucleus/Median Eminence",
         SRA_ID = "SRR19578591")
DefaultAssay(object = Lutomska2022_arc_astro) <- "RNA"
Lutomska2022_arc_astro <-
  Lutomska2022_arc_astro |> 
  DietSeurat(assays = "RNA")


DefaultAssay(object = Deng2020_arc_all) <- "RNA"
Deng2020_arc_all@meta.data <-
  Deng2020_arc_all@meta.data |>
  select(nCount_RNA:nFeature_SCT, study_id, sex, tech, subsets_mito_percent, ident, seurat_clusters) |> 
  rename(Technology = tech,
         percent_mt = subsets_mito_percent,
         Sex = sex,
         Dataset = study_id,
         Batch_ID = ident) |> 
  mutate(Author_Region = "Arcuate Nucleus/Median Eminence",
         Batch_ID = str_c("Deng10xv3", Batch_ID, sep = "_"),
         Sex = if_else(Sex == "male", "M", "F"),
         Dataset = "Deng10x")
Deng2020_arc <- 
  subset(Deng2020_arc_all, 
         subset = seurat_clusters %in% c(3,6,7)) |>
  DietSeurat(assays = "RNA")

Lutomska2022_arc_all@meta.data <-
  Lutomska2022_arc_all@meta.data |>
  select(-(SCT_snn_res.0.01:k_tree)) |> 
  rename(Batch_ID = orig.ident) |> 
  mutate(Author_Region = "Arcuate Nucleus/Median Eminence",
         SRA_ID = "SRR19578591")
DefaultAssay(object = Lutomska2022_arc_all) <- "RNA"
Lutomska2022_arc_all <-
  Lutomska2022_arc_all |> 
  DietSeurat(assays = "RNA")
gc()
```

Visualise astrocytes

```{r pl-all-orginally-integrated-astrocytes}
plEmbOrig <- DimPlot(astroMap, reduction = "umap_scvi",
                     group.by = "Batch_ID", 
                     label = TRUE, repel = TRUE) + NoLegend()
plEmbOrig
```

```{r pl-all-not-integrated-astrocytes, fig.width=12, fig.asp=0.309}
astroMap <- merge(astroMap, y = c(Deng2020_arc_astro, Lutomska2022_arc_astro), project = "hypothalamic_astrocytes")
astroMap

astroMap <-
  SCTransform(astroMap, vst.flavor = "v2",
              # vars.to.regress = "percent_mt",
              method = "glmGamPoi",
              variable.features.n = 5000,
              return.only.var.genes = FALSE,
              seed.use = reseed,
              verbose = FALSE) |> 
  RunPCA(seed.use = reseed,
         verbose = FALSE) |> 
  RunUMAP(reduction = "pca", 
          densmap = TRUE, dims = 1:50, 
          seed.use = reseed, verbose = FALSE)
plEmbRawBatch <- DimPlot(astroMap, reduction = "umap", 
                         group.by = "Batch_ID", 
                         label = TRUE, repel = TRUE) + NoLegend()
plEmbRawReg <- DimPlot(astroMap, reduction = "umap", 
                       group.by = "Author_Region",
                       label = TRUE, repel = TRUE) + NoLegend()
plEmbRawBatch + plEmbRawReg
```

Integration of astrocytes

```{r integration-features-astrocytes}
srt_list <- Seurat::SplitObject(astroMap, split.by = "Batch_ID")
srt_list <- lapply(X = srt_list,
                   vst.flavor = "v2",
                   FUN = SCTransform,
                   # vars.to.regress = "percent_mt",
                   method = "glmGamPoi",
                   variable.features.n = 5000,
                   return.only.var.genes = FALSE,
                   seed.use = reseed,
                   verbose = FALSE)
features <- SelectIntegrationFeatures(object.list = srt_list, nfeatures = 3000, verbose = FALSE)

```

```{r integration-object-astrocytes}
srt_list <- 
  srt_list[
    !(map(srt_list, ncol) |>
      map(~ .x < 99) |>
      simplify())
    ]

npcs <- 50
srt_list <- lapply(X = srt_list, FUN = RunPCA, features = features, npcs = npcs, seed.use = reseed, verbose = FALSE)

srt_list <- PrepSCTIntegration(object.list = srt_list, anchor.features = features)

anchors <- FindIntegrationAnchors(
  object.list = srt_list,
  normalization.method = "SCT",
  anchor.features = features,
  reduction = "rpca",
  dims = 1:30,
  k.anchor = 20,
  verbose = FALSE
)

combined_sct <- IntegrateData(
  anchorset = anchors,
  normalization.method = "SCT",
  dims = 1:30,
  verbose = FALSE
)

metadata = combined_sct@meta.data
rownames(metadata) = colnames(combined_sct)
ref.labels = metadata$Author_Region
combined_sct <-
  RunPCA(combined_sct, npcs = npcs, 
         seed.use = reseed, verbose = FALSE)
combined_sct
```

```{r pl-clustree, fig.width=10, fig.asp=1.618}
combined_sct <- combined_sct |> 
  RunUMAP(reduction = "pca", return.model = TRUE,
          densmap = TRUE, dims = 1:npcs, 
          seed.use = reseed, verbose = FALSE) |> 
  FindNeighbors(reduction = "pca", dims = 1:npcs, verbose = FALSE)

resolutions <-
  modularity_event_sampling(
    A = combined_sct@graphs$integrated_snn,
    n.res = 30,
    gamma.min = 0.01,
    gamma.max = 2.5
  ) # sample based on the similarity matrix

# clustering using Suerat
combined_sct <- combined_sct |> 
  FindClusters(algorithm = 4, method = "igraph",
               resolution = resolutions, random.seed = reseed,
               verbose = FALSE)

# initial cluster tree from Seurat flat clustering
plot_clustree(
  labelmat = combined_sct@meta.data,
  prefix = 'integrated_snn_res.',
  ref.labels = ref.labels,
  plot.ref = FALSE
)
```

```{r pl-mrtree, fig.height=6, fig.width=11, echo=TRUE, include=FALSE}
out <-  mrtree(
  combined_sct,
  prefix = 'integrated_snn_res.',
  n.cores = n_cores,
  consensus = FALSE,
  augment.path = FALSE
)
# if there are few partitions per k, within resolution consensus step can speed up the algorithm
# weight per sample is encoraged if the classes are imbalanced

plot_tree(
  labelmat = out$labelmat.mrtree,
  ref.labels = ref.labels,
  plot.piechart = TRUE,
  node.size = 0.2,
  tip.label.dist = 10,
  bottom.margin = 30
)
```

```{r pl-clustering-amri}
# Adjusted Multiresolution Rand Index (AMRI)
ks.flat <-  apply(
  out$labelmat.flat,
  2,
  FUN = function(x)
    length(unique(x))
)
ks.mrtree <-  apply(
  out$labelmat.mrtree,
  2,
  FUN = function(x)
    length(unique(x))
)
amri.flat <-  sapply(1:ncol(out$labelmat.flat), function(i)
  AMRI(out$labelmat.flat[, i], ref.labels)$amri)
amri.flat <-  aggregate(amri.flat, by = list(k = ks.flat), FUN = mean)
amri.recon <-  sapply(1:ncol(out$labelmat.mrtree), function(i)
  AMRI(out$labelmat.mrtree[, i], ref.labels)$amri)

df <-  rbind(
  data.frame(
    k = amri.flat$k,
    amri = amri.flat$x,
    method = 'Seurat flat'
  ),
  data.frame(k = ks.mrtree, amri = amri.recon, method = 'MRtree')
)
ggplot2::ggplot(data = df, aes(x = k, y = amri, color = method)) + geom_line() + theme_bw()
```

```{r pl-clustering-resolution, fig.width=5}
stab.out <- stability_plot(out)
stab.out$plot
```

Plot by nucleus

```{r pl-all-integrated-astrocytes-nucleus, fig.width=12, fig.asp=0.309}
plEmbCombBatch <- DimPlot(combined_sct, reduction = "umap",
                          group.by = "Batch_ID",
                          label = TRUE, repel = TRUE) + NoLegend()
plEmbCombReg <- DimPlot(combined_sct, reduction = "umap",
                        group.by = "Author_Region",
                        label = TRUE, repel = TRUE) + NoLegend()
plEmbCombBatch + plEmbCombReg
```

```{r pl-clustering, fig.height=5, fig.width=8}
combined_sct$k_tree <- as.factor(out$labelmat.mrtree[, "K17"])
p1 <- DimPlot(combined_sct, label = T, repel = T) + ggtitle("Unsupervised clustering") + NoLegend()
p2 <- DimPlot(combined_sct, label = T, repel = T, group.by = "k_tree") + ggtitle("MRTree") + NoLegend()

p1 | p2
```

```{r pl-schex}
library(schex)
combined_sct <- make_hexbin(combined_sct, nbins = 60, dimension_reduction = "UMAP")
plot_hexbin_density(combined_sct)
plot_hexbin_meta(combined_sct, col = "nCount_RNA", action = "median")
plot_hexbin_meta(combined_sct, col = "k_tree", action = "majority")
```

```{r pl-schex-k-tree}
label_df <- make_hexbin_label(combined_sct, col = "k_tree")
pp <- plot_hexbin_meta(combined_sct, col = "k_tree", action = "majority")
pp + ggrepel::geom_label_repel(data = label_df, aes(x = x, y = y, label = label), colour = "black", 
    label.size = NA, fill = NA)
```

```{r pl-schex-regions}
reg_df <- make_hexbin_label(combined_sct, 
                            col = "Author_Region")
pp2 <- plot_hexbin_meta(combined_sct,
                        col = "Author_Region",
                        action = "majority")
pp2 + ggrepel::geom_label_repel(data = reg_df, 
                                aes(x = x, y = y,
                                    label = label), 
                                colour = "black",
                                label.size = NA, fill = NA)
```

```{r markers-tables}
Idents(combined_sct) <- "k_tree"
srt.markers <- FindAllMarkers(combined_sct, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
readr::write_csv(srt.markers, 
                 here(tables_dir,
                      'astr_k17-mrk_wilcox-sct.csv'))
srt.markers %>%
    group_by(cluster) %>%
    slice_max(n = 3, order_by = avg_log2FC)

```

```{r pl-heatmap, fig.width = 14, fig.asp = 0.868}
srt.markers %>%
    group_by(cluster) %>%
    top_n(n = 10, wt = avg_log2FC) -> top10
DoHeatmap(combined_sct, features = top10$gene, 
          size = 4, angle = 90) + NoLegend()
```

```{r pl-all-integrated-astrocytes-init-canon-markers, fig.width=12}
plEmbCombCMrk <- FeaturePlot(
  combined_sct,
  features = genes.embed[genes.embed %in%
                           rownames(combined_sct@assays$SCT@data)],
  min.cutoff = "q10", max.cutoff = "q90",
  ncol = 3
)
plEmbCombCMrk
```

```{r pl-all-integrated-astrocytes-init-canon-mrk-density, fig.width=12}
genes.embed[genes.embed %in% rownames(combined_sct@assays$SCT@data)] |>
  map(~ plot_density(combined_sct, .x))
```

```{r save}
if (!file.exists(here(data_dir, "comb_astrocytes.h5Seurat"))) {
  SaveH5Seurat(combined_sct, 
               filename = here(data_dir, "comb_astrocytes.h5Seurat"))
  Convert(here(data_dir, "comb_astrocytes.h5Seurat"), 
          dest = "h5ad")
}
```
